name: gtads_sigmob
description: 为GTAds提供Singmob广告支持
version: 1.5.0
homepage: https://github.com/gstory0404/GTAds/tree/master/gtads_sigmob

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  sigmobad: ^1.1.2
  gtads: ^1.5.0
#  gtads:
#    path: ../gtads

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.gstory.gtads_sigmob
        pluginClass: GtadsSigmobPlugin
      ios:
        pluginClass: GtadsSigmobPlugin
